In [196]:
import pandas as pd
import numpy as np

In [197]:
df = pd.read_csv("/content/diabetic_data.csv")
df.head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  

[5 rows x 50 columns]

In [198]:
df.shape

(101766, 50)

In [199]:
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazo

In [200]:
#there are many rows with ?, we are replacing them with nan
df.replace("?", np.nan, inplace=True)

In [201]:
df.isna().sum()

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide 

In [202]:
df.shape

(101766, 50)

In [203]:
df.dtypes

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride         

In [204]:
df.head(1)

encounter_id  patient_nbr       race  gender     age weight  \
0       2278392      8222157  Caucasian  Female  [0-10)    NaN   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  

[1 rows x 50 columns]

In [205]:
#geting unique values in the column
df.race.unique()

array(['Caucasian', 'AfricanAmerican', nan, 'Other', 'Asian', 'Hispanic'],
      dtype=object)

In [206]:
#using a manual encoding first, will create a function to do this later
print(f"Mode value of race is {df.race.mode()}")
#replcae each unique value with a distinctive digit
df.race.replace(['Caucasian', 'AfricanAmerican', 'Other', 'Asian', 'Hispanic'], [0,1,2,3,4], inplace=True)
#and replcing nan with the mode
df.race.replace(np.nan, 0, inplace=True)
#changing the data type to int
df.race = df.race.astype("int")

Mode value of race is 0    Caucasian
dtype: object


In [207]:
df.race.mode()

0    0
dtype: int64

In [208]:
df.race.unique()

array([0, 1, 2, 3, 4])

In [209]:
df.gender.unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [210]:
#repeating samething done for race here again
print(df.gender.mode())
df.gender = df.gender.replace(['Female', 'Male', 'Unknown/Invalid'], [0,1,0]).astype("int32")

0    Female
dtype: object


In [211]:
df.age.unique()

array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
       '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object)

In [212]:
#replacing the values with their min range each as observered in the dataset
df.age = df.age.replace(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)'
                        , '[50-60)', '[60-70)', '[70-80)', '[80-90)', '[90-100)'],
                        [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]).astype("int32")

In [213]:
df.weight.unique()

array([nan, '[75-100)', '[50-75)', '[0-25)', '[100-125)', '[25-50)',
       '[125-150)', '[175-200)', '[150-175)', '>200'], dtype=object)

In [214]:
df.weight.mode()

0    [75-100)
dtype: object

In [215]:
#using the methods applied above here again and also manually repplacing the nan with the mode
df.weight = df.weight.replace([np.nan, '[75-100)', '[50-75)', '[0-25)', '[100-125)',
                               '[25-50)','[125-150)', '[175-200)', '[150-175)',
                               '>200'], [75, 75, 50, 0, 100, 25, 125, 175, 150, 200])

In [216]:
df.admission_type_id.unique()

array([6, 1, 2, 3, 4, 5, 8, 7])

In [217]:
df.discharge_disposition_id.unique()

array([25,  1,  3,  6,  2,  5, 11,  7, 10,  4, 14, 18,  8, 13, 12, 16, 17,
       22, 23,  9, 20, 15, 24, 28, 19, 27])

In [218]:
df.admission_source_id.unique()

array([ 1,  7,  2,  4,  5,  6, 20,  3, 17,  8,  9, 14, 10, 22, 11, 25, 13])

In [219]:
df.time_in_hospital.unique()

array([ 1,  3,  2,  4,  5, 13, 12,  9,  7, 10,  6, 11,  8, 14])

In [220]:
df.payer_code.unique()

array([nan, 'MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM',
       'CH', 'PO', 'WC', 'OT', 'OG', 'MP', 'FR'], dtype=object)

In [221]:
df.payer_code.mode()

0    MC
dtype: object

In [222]:
#repeating same methode here again
df.payer_code = df.payer_code.replace([np.nan, 'MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM',
       'CH', 'PO', 'WC', 'OT', 'OG', 'MP', 'FR'], [0, 0, 1, 2, 3, 4, 5, 6, 7, 8,
                                                   9, 10, 11, 12, 13, 14, 15, 16]).astype("int32")

In [223]:
df.payer_code.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int32)

In [224]:
df.medical_specialty.unique()

array(['Pediatrics-Endocrinology', nan, 'InternalMedicine',
       'Family/GeneralPractice', 'Cardiology', 'Surgery-General',
       'Orthopedics', 'Gastroenterology',
       'Surgery-Cardiovascular/Thoracic', 'Nephrology',
       'Orthopedics-Reconstructive', 'Psychiatry', 'Emergency/Trauma',
       'Pulmonology', 'Surgery-Neuro',
       'Obsterics&Gynecology-GynecologicOnco', 'ObstetricsandGynecology',
       'Pediatrics', 'Hematology/Oncology', 'Otolaryngology',
       'Surgery-Colon&Rectal', 'Pediatrics-CriticalCare', 'Endocrinology',
       'Urology', 'Psychiatry-Child/Adolescent', 'Pediatrics-Pulmonology',
       'Neurology', 'Anesthesiology-Pediatric', 'Radiology',
       'Pediatrics-Hematology-Oncology', 'Psychology', 'Podiatry',
       'Gynecology', 'Oncology', 'Pediatrics-Neurology',
       'Surgery-Plastic', 'Surgery-Thoracic',
       'Surgery-PlasticwithinHeadandNeck', 'Ophthalmology',
       'Surgery-Pediatric', 'Pediatrics-EmergencyMedicine',
       'PhysicalMedicineandRe

In [225]:
df.medical_specialty.mode()

0    InternalMedicine
dtype: object

In [226]:
medical_specialty = ['Pediatrics-Endocrinology', np.nan, 'InternalMedicine',
       'Family/GeneralPractice', 'Cardiology', 'Surgery-General',
       'Orthopedics', 'Gastroenterology',
       'Surgery-Cardiovascular/Thoracic', 'Nephrology',
       'Orthopedics-Reconstructive', 'Psychiatry', 'Emergency/Trauma',
       'Pulmonology', 'Surgery-Neuro',
       'Obsterics&Gynecology-GynecologicOnco', 'ObstetricsandGynecology',
       'Pediatrics', 'Hematology/Oncology', 'Otolaryngology',
       'Surgery-Colon&Rectal', 'Pediatrics-CriticalCare', 'Endocrinology',
       'Urology', 'Psychiatry-Child/Adolescent', 'Pediatrics-Pulmonology',
       'Neurology', 'Anesthesiology-Pediatric', 'Radiology',
       'Pediatrics-Hematology-Oncology', 'Psychology', 'Podiatry',
       'Gynecology', 'Oncology', 'Pediatrics-Neurology',
       'Surgery-Plastic', 'Surgery-Thoracic',
       'Surgery-PlasticwithinHeadandNeck', 'Ophthalmology',
       'Surgery-Pediatric', 'Pediatrics-EmergencyMedicine',
       'PhysicalMedicineandRehabilitation', 'InfectiousDiseases',
       'Anesthesiology', 'Rheumatology', 'AllergyandImmunology',
       'Surgery-Maxillofacial', 'Pediatrics-InfectiousDiseases',
       'Pediatrics-AllergyandImmunology', 'Dentistry', 'Surgeon',
       'Surgery-Vascular', 'Osteopath', 'Psychiatry-Addictive',
       'Surgery-Cardiovascular', 'PhysicianNotFound', 'Hematology',
       'Proctology', 'Obstetrics', 'SurgicalSpecialty', 'Radiologist',
       'Pathology', 'Dermatology', 'SportsMedicine', 'Speech',
       'Hospitalist', 'OutreachServices', 'Cardiology-Pediatric',
       'Perinatology', 'Neurophysiology', 'Endocrinology-Metabolism',
       'DCPTEAM', 'Resident']

In [227]:
#basically repeating samething above, as the unique values are much I am using a loop here and manually replacing the value of the nan using the mode
med_replace = [i for i in range((len(medical_specialty)))]
med_replace[1] = 2
med_replace[:5]

[0, 2, 2, 3, 4]

In [228]:
df.medical_specialty = df.medical_specialty.replace(medical_specialty, med_replace).astype("int32")

In [229]:
df.iloc[:,12:18].isna().sum()

num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
dtype: int64

In [230]:
df.iloc[:,18:21].isnull().sum()

diag_1      21
diag_2     358
diag_3    1423
dtype: int64

In [231]:
df.diag_1.mode()

0    428
dtype: object

In [232]:
df.diag_1.nunique()

716

In [233]:
df.race.mode()

0    0
dtype: int64

In [234]:
#replacing nan with the mode
df.diag_1.replace(np.nan, 428, inplace=True)
# index_all = [x for x in range(df.diag_1.nunique())]
# df.diag_1 = df.diag_1.replace(df.diag_1.unique(), index_all).astype("int32")

In [235]:
df.diag_2.mode()

0    276
dtype: object

In [236]:
#replacing nan with the mode
df.diag_2.replace(np.nan, 276, inplace=True)
# index_all = [x for x in range(df.diag_2.nunique())]
# df.diag_2 = df.diag_2.replace(df.diag_2.unique(), index_all).astype("int32")

In [237]:
df.diag_3.mode()

0    250
dtype: object

In [238]:
#replacing nan with the mode
df.diag_3.replace(np.nan, 250, inplace=True)
# index_all = [x for x in range(df.diag_3.nunique())]
# df.diag_3 = df.diag_3.replace(df.diag_3.unique(), index_all).astype("int32")

In [239]:
#using a function to do the encoding
def encoder(x):
  #create some sort of unique index for all unique value
  index_all = [x_i for x_i in range(x.nunique())]
  #replace the unique value with the index and covert the type to int
  x = x.replace(x.unique(), index_all).astype("int32")

  return x

In [240]:
#apply it to the next 3 columns to be processed
df.iloc[:, 18:21] = df.iloc[:, 18:21].apply(encoder)

In [241]:
df.iloc[:, 18:21].head()

diag_1  diag_2  diag_3
0       0       0       0
1       1       1       1
2       2       2       2
3       3       3       3
4       4       4       4

In [242]:
#applying it to the rest of the colum
df.iloc[:, 22:] = df.iloc[:, 22:].apply(encoder)

In [243]:
df.iloc[:, 22:].head()

max_glu_serum  A1Cresult  metformin  repaglinide  nateglinide  \
0              0          0          0            0            0   
1              0          0          0            0            0   
2              0          0          0            0            0   
3              0          0          0            0            0   
4              0          0          0            0            0   

   chlorpropamide  glimepiride  acetohexamide  glipizide  glyburide  ...  \
0               0            0              0          0          0  ...   
1               0            0              0          0          0  ...   
2               0            0              0          1          0  ...   
3               0            0              0          0          0  ...   
4               0            0              0          1          0  ...   

   citoglipton  insulin  glyburide-metformin  glipizide-metformin  \
0            0        0                    0                    0   
1            0        1                    0                    0   
2            0        0                    0                    0   
3            0        1                    0                    0   
4            0        2                    0                    0   

   glimepiride-pioglitazone  metformin-rosiglitazone  metformin-pioglitazone  \
0                         0                        0                       0   
1                         0                        0                       0   
2                         0                        0                       0   
3                         0                        0                       0   
4                         0                        0                       0   

   change  diabetesMed  readmitted  
0       0            0           0  
1       1            1           1  
2       0            1           0  
3       1            1           0  
4       1            1           0  

[5 rows x 28 columns]

In [244]:
df.dtypes

encounter_id                int64
patient_nbr                 int64
race                        int64
gender                      int32
age                         int32
weight                      int64
admission_type_id           int64
discharge_disposition_id    int64
admission_source_id         int64
time_in_hospital            int64
payer_code                  int32
medical_specialty           int32
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                      int32
diag_2                      int32
diag_3                      int32
number_diagnoses            int64
max_glu_serum               int32
A1Cresult                   int32
metformin                   int32
repaglinide                 int32
nateglinide                 int32
chlorpropamide              int32
glimepiride                 int32
acetohexamide 

In [245]:
df.isna().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazo

In [246]:
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazo

In [254]:
# saving the DataFrame as a CSV file
data = df.to_csv('processed_diabetic_data.csv', index = False)

In [255]:
df_new = pd.read_csv("/content/processed_diabetic_data.csv")

In [256]:
df_new.head()

encounter_id  patient_nbr  race  gender  age  weight  admission_type_id  \
0       2278392      8222157     0       0    0      75                  6   
1        149190     55629189     0       0   10      75                  1   
2         64410     86047875     1       0   20      75                  1   
3        500364     82442376     0       1   30      75                  1   
4         16680     42519267     0       1   40      75                  1   

   discharge_disposition_id  admission_source_id  time_in_hospital  ...  \
0                        25                    1                 1  ...   
1                         1                    7                 3  ...   
2                         1                    7                 2  ...   
3                         1                    7                 2  ...   
4                         1                    7                 1  ...   

   citoglipton  insulin  glyburide-metformin  glipizide-metformin  \
0            0        0                    0                    0   
1            0        1                    0                    0   
2            0        0                    0                    0   
3            0        1                    0                    0   
4            0        2                    0                    0   

   glimepiride-pioglitazone  metformin-rosiglitazone  metformin-pioglitazone  \
0                         0                        0                       0   
1                         0                        0                       0   
2                         0                        0                       0   
3                         0                        0                       0   
4                         0                        0                       0   

   change  diabetesMed  readmitted  
0       0            0           0  
1       1            1           1  
2       0            1           0  
3       1            1           0  
4       1            1           0  

[5 rows x 50 columns]

In [258]:
df_new.dtypes

encounter_id                int64
patient_nbr                 int64
race                        int64
gender                      int64
age                         int64
weight                      int64
admission_type_id           int64
discharge_disposition_id    int64
admission_source_id         int64
time_in_hospital            int64
payer_code                  int64
medical_specialty           int64
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                      int64
diag_2                      int64
diag_3                      int64
number_diagnoses            int64
max_glu_serum               int64
A1Cresult                   int64
metformin                   int64
repaglinide                 int64
nateglinide                 int64
chlorpropamide              int64
glimepiride                 int64
acetohexamide 